server {
    listen 80;
    
    # Rute untuk file statik UI React (Hasil Vite Build)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # Fallback untuk React Router DOM
    }

    # Rute Proxy agar API dapat diakses dalam jaringan container (Backend:5000)
    # Ini menyelesaikan masalah CORS sepenuhnya!
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
